lexical: 
	flex func.lex
	gcc -c lex.yy.c
	gcc -c lex.c
	gcc -c print.c
	gcc -o lexical lex.yy.o print.o lex.o

parser: 
	flex func.lex
	gcc -c lex.yy.c
	gcc -c parse.c
	gcc -c print.c	
	gcc -o parser print.o lex.yy.o parse.o

parser2:
	flex func.lex
	gcc -c lex.yy.c
	gcc -c parse_2.c
	gcc -c print.c
	gcc -o parser2 print.o lex.yy.o parse_2.o

clean:
	rm -rf *.o simp.c lex.yy.c lexical parser parser2
